@echo off
title RuralRefLink - PostgreSQL setup

set "ROOT=%~dp0"
set "BACKEND=%ROOT%backend"
set "RESET=0"
if /i "%~1"=="--reset" set "RESET=1"

echo ==============================================================
echo   RuralRefLink - PostgreSQL database setup
echo ==============================================================
echo.

REM ---- Locate the PostgreSQL client ----------------------------------------
call "%ROOT%scripts\find_psql.bat"
if not defined PSQL (
    echo [ERROR] Could not find psql.exe.
    echo         Install PostgreSQL ^(with "Command Line Tools"^) and try again:
    echo         https://www.postgresql.org/download/windows/
    echo.
    pause
    exit /b 1
)
echo Using client: %PSQL%
echo.

REM ---- Ask for the superuser password (once) -------------------------------
set "PGPASS="
set /p "PGPASS=Password for PostgreSQL user 'postgres': "
if not defined PGPASS (
    echo [ERROR] No password entered - nothing to do.
    echo.
    pause
    exit /b 1
)
set "PGPASSWORD=%PGPASS%"

REM Keep psql's NOTICE chatter out of the console output
set "PGOPTIONS=-c client_min_messages=warning"

REM ---- Check the server is reachable --------------------------------------
echo.
echo Connecting to PostgreSQL on localhost:5432 ...
"%PSQL%" -h localhost -p 5432 -U postgres -d postgres -w -tAc "SELECT 1" >nul 2>&1
if errorlevel 1 (
    echo.
    echo [ERROR] Could not connect to PostgreSQL. Please check that:
    echo           1^) the PostgreSQL service is running
    echo           2^) the password is correct
    echo           3^) the server is listening on port 5432
    echo.
    pause
    exit /b 1
)
echo       connected - OK
echo.

REM ---- Optional full reset ------------------------------------------------
if "%RESET%"=="1" (
    echo [reset] Dropping database 'ruralref' if it exists ...
    "%PSQL%" -h localhost -p 5432 -U postgres -d postgres -w -q -f "%ROOT%scripts\drop_database.sql"
    echo         done.
    echo.
)

REM ---- Create role + database (idempotent) --------------------------------
echo [1/2] Creating role 'ruralref' and database 'ruralref' ^(existing ones are kept^) ...
"%PSQL%" -h localhost -p 5432 -U postgres -d postgres -w -q -f "%ROOT%scripts\bootstrap_database.sql"
if errorlevel 1 (
    echo.
    echo [ERROR] Database bootstrap failed - see the message above.
    echo.
    pause
    exit /b 1
)
echo       done.
echo.

REM ---- Write backend\.env -------------------------------------------------
echo [2/2] Writing backend\.env ...
if exist "%BACKEND%\.env" (
    copy /y "%BACKEND%\.env" "%BACKEND%\.env.backup" >nul
    echo       existing backend\.env saved as backend\.env.backup
)
(
    echo # Generated by setup_database.bat
    echo # RuralRefLink backend - local PostgreSQL configuration
    echo DATABASE_URL=postgresql+psycopg://ruralref:ruralref@localhost:5432/ruralref
    echo JWT_SECRET=ruralreflink_super_secret_jwt_signing_key_change_in_production_2026
) > "%BACKEND%\.env"
echo       done.
echo.

REM ---- Verify -------------------------------------------------------------
echo [verify] Connecting as 'ruralref' ...
set "PGPASSWORD=ruralref"
"%PSQL%" -h localhost -p 5432 -U ruralref -d ruralref -w -tAc "SELECT 'OK - connected to ' || current_database() || ' as ' || current_user"
if errorlevel 1 (
    echo.
    echo [ERROR] The database was created but connecting to it failed.
    echo.
    pause
    exit /b 1
)
echo.

echo ==============================================================
echo   Database is ready.
echo.
echo   Next steps:
echo     run_backend.bat    - starts the API, creates tables + demo data
echo     run_frontend.bat   - starts the web UI
echo     show_database.bat  - displays the live database
echo ==============================================================
echo.
pause
